// // HTML
const quizQuestions = [
    {
      id: 1,
      question: "What does HTML stand for?",
      options: [
        "Hyperlinks and Text Markup Language",
        "Home Tool Markup Language",
        "Hyper Text Markup Language",
        "High Text Markup Language",
      ],
      correct: "Hyper Text Markup Language",
    },
    {
      id: 2,
      question: "Which HTML tag is used to define an internal stylesheet?",
      options: ["<style>", "<css>", "<script>", "<link>"],
      correct: "<style>",
    },
    {
      id: 3,
      question:
        "Which HTML element is used to specify a header for a document or section?",
      options: ["<header>", "<section>", "<head>", "<title>"],
      correct: "<header>",
    },
    {
      id: 4,
      question: "What is the correct HTML element for inserting a line break?",
      options: ["<br>", "<lb>", "<break>", "<hr>"],
      correct: "<br>",
    },
    {
      id: 5,
      question: "Which HTML tag is used to create an unordered list?",
      options: ["<ul>", "<ol>", "<li>", "<list>"],
      correct: "<ul>",
    },
    {
      id: 6,
      question: "What is the correct syntax for creating a hyperlink in HTML?",
      options: [
        '<a href="https://example.com">Visit</a>',
        '<a src="https://example.com">Visit</a>',
        '<link href="https://example.com">Visit</link>',
        "<a>Visit https://example.com</a>",
      ],
      correct: '<a href="https://example.com">Visit</a>',
    },
    {
      id: 7,
      question: "What is the purpose of the <alt> attribute in the <img> tag?",
      options: [
        "To specify the image size",
        "To provide an alternative text for the image",
        "To define the image source",
        "To set the image alignment",
      ],
      correct: "To provide an alternative text for the image",
    },
    {
      id: 8,
      question: "Which HTML tag is used to define a table row?",
      options: ["<td>", "<tr>", "<th>", "<table-row>"],
      correct: "<tr>",
    },
    {
      id: 9,
      question: "What is the correct way to specify a background color in HTML?",
      options: [
        '<body style="background-color:blue;">',
        '<background-color="blue">',
        '<body color="blue">',
        '<body background="blue">',
      ],
      correct: '<body style="background-color:blue;">',
    },
    {
      id: 10,
      question:
        "Which HTML element is used to display a scalar measurement within a range?",
      options: ["<meter>", "<progress>", "<range>", "<input>"],
      correct: "<meter>",
    },
    {
      id: 11,
      question: "What is the correct HTML element for the largest heading?",
      options: ["<h1>", "<h6>", "<header>", "<heading>"],
      correct: "<h1>",
    },
    {
      id: 12,
      question: "Which HTML tag is used to create a dropdown list?",
      options: ["<select>", "<dropdown>", "<option>", "<list>"],
      correct: "<select>",
    },
    {
      id: 13,
      question: "What is the correct HTML for making a checkbox?",
      options: [
        '<input type="checkbox">',
        '<input type="check">',
        "<checkbox>",
        "<check>",
      ],
      correct: '<input type="checkbox">',
    },
    {
      id: 14,
      question: "Which attribute specifies the destination of a link in HTML?",
      options: ["href", "src", "link", "destination"],
      correct: "href",
    },
    {
      id: 15,
      question: "Which HTML tag is used to define an inline frame?",
      options: ["<iframe>", "<frame>", "<inline>", "<iFrame>"],
      correct: "<iframe>",
    },
    {
      id: 16,
      question: "What is the correct way to write a comment in HTML?",
      options: [
        "<!-- This is a comment -->",
        "// This is a comment",
        "'This is a comment",
        "** This is a comment **",
      ],
      correct: "<!-- This is a comment -->",
    },
    {
      id: 17,
      question:
        "Which HTML attribute specifies an input field that must be filled out?",
      options: ["required", "validate", "mandatory", "placeholder"],
      correct: "required",
    },
    {
      id: 18,
      question: "What is the correct HTML element to embed a video?",
      options: ["<video>", "<media>", "<movie>", "<embed>"],
      correct: "<video>",
    },
    {
      id: 19,
      question: "Which HTML tag is used to define a description list?",
      options: ["<dl>", "<list>", "<dt>", "<dd>"],
      correct: "<dl>",
    },
    {
      id: 20,
      question: "Which input type is used for entering a date in HTML?",
      options: ["date", "datetime-local", "text", "calendar"],
      correct: "date",
    },
    {
      id: 21,
      question: "Which HTML attribute specifies the source file of a script?",
      options: ["src", "href", "script", "file"],
      correct: "src",
    },
    {
      id: 22,
      question: "What is the purpose of the <fieldset> element in HTML?",
      options: [
        "To group related elements in a form",
        "To create a box around text",
        "To define a section in a document",
        "To apply a border to images",
      ],
      correct: "To group related elements in a form",
    },
    {
      id: 23,
      question: "What is the correct HTML element for playing audio files?",
      options: ["<audio>", "<sound>", "<music>", "<media>"],
      correct: "<audio>",
    },
    {
      id: 24,
      question: "What is the purpose of the <legend> tag in HTML?",
      options: [
        "To define a caption for a <fieldset>",
        "To create a legend for an image",
        "To add a title to a table",
        "To format text as bold",
      ],
      correct: "To define a caption for a <fieldset>",
    },
    {
      id: 25,
      question: "Which tag is used to define an ordered list in HTML?",
      options: ["<ol>", "<ul>", "<list>", "<order>"],
      correct: "<ol>",
    },
    {
      id: 26,
      question: "Which HTML tag is used to insert an image?",
      options: ["<img>", "<picture>", "<src>", "<image>"],
      correct: "<img>",
    },
    {
      id: 27,
      question: "What does the <noscript> tag define?",
      options: [
        "Alternate content for users without JavaScript",
        "An additional script to execute",
        "No JavaScript usage",
        "A warning for deprecated JavaScript",
      ],
      correct: "Alternate content for users without JavaScript",
    },
    {
      id: 28,
      question: "What is the correct HTML element for emphasizing text?",
      options: ["<em>", "<italic>", "<i>", "<strong>"],
      correct: "<em>",
    },
    {
      id: 29,
      question:
        "Which HTML tag is used to define a container for external content?",
      options: ["<div>", "<container>", "<section>", "<iframe>"],
      correct: "<iframe>",
    },
    {
      id: 30,
      question: "What is the purpose of the <nav> tag in HTML?",
      options: [
        "To define a navigation section",
        "To create a menu",
        "To define a navigation link",
        "To embed a map",
      ],
      correct: "To define a navigation section",
    },
  {
  id: 31,
  question: "What does CSS stand for?",
  options: [
    "Creative Style Sheets",
    "Cascading Style Sheets",
    "Colorful Style Sheets",
    "Computer Style Sheets",
  ],
  correct: "Cascading Style Sheets",
},
{
  id: 32,
  question: "Which property is used to change the text color in CSS?",
  options: ["color", "text-color", "font-color", "foreground-color"],
  correct: "color",
},
{
  id: 33,
  question: "How do you add an external CSS file to an HTML document?",
  options: [
    "<link rel='stylesheet' href='styles.css'>",
    "<style src='styles.css'>",
    "<stylesheet href='styles.css'>",
    "<css-link href='styles.css'>",
  ],
  correct: "<link rel='stylesheet' href='styles.css'>",
},
{
  id: 34,
  question: "Which property is used to set the background color of an element?",
  options: ["background", "bg-color", "background-color", "color"],
  correct: "background-color",
},
{
  id: 35,
  question: "What is the default value of the `position` property in CSS?",
  options: ["static", "absolute", "relative", "fixed"],
  correct: "static",
},
{
  id: 36,
  question: "Which property controls the font size of an element?",
  options: ["font-size", "font-style", "text-size", "font-weight"],
  correct: "font-size",
},
{
  id: 37,
  question: "How do you select an element with the ID `header` in CSS?",
  options: ["#header", ".header", "header", "id=header"],
  correct: "#header",
},
{
  id: 38,
  question: "Which property is used to create space inside an element's border?",
  options: ["padding", "margin", "spacing", "border-spacing"],
  correct: "padding",
},
{
  id: 39,
  question: "Which property is used to create space outside an element's border?",
  options: ["margin", "padding", "gap", "border-spacing"],
  correct: "margin",
},
{
  id: 40,
  question: "What is the correct syntax for a CSS comment?",
  options: [
    "// This is a comment",
    "<!-- This is a comment -->",
    "/* This is a comment */",
    "### This is a comment ###",
  ],
  correct: "/* This is a comment */",
},
{
  id: 41,
  question: "Which property is used to make text italic in CSS?",
  options: ["font-style", "font-variant", "text-style", "font-weight"],
  correct: "font-style",
},
{
  id: 42,
  question: "What is the correct order of the box model in CSS?",
  options: [
    "Content > Padding > Border > Margin",
    "Content > Margin > Border > Padding",
    "Padding > Content > Border > Margin",
    "Margin > Border > Padding > Content",
  ],
  correct: "Content > Padding > Border > Margin",
},
{
  id: 43,
  question: "Which property is used to set the underline of text?",
  options: ["text-decoration", "font-style", "underline", "text-transform"],
  correct: "text-decoration",
},
{
  id: 44,
  question: "Which CSS property is used to make text bold?",
  options: ["font-weight", "font-style", "text-weight", "bold"],
  correct: "font-weight",
},
{
  id: 45,
  question: "Which CSS unit is relative to the font-size of the root element?",
  options: ["em", "rem", "px", "pt"],
  correct: "rem",
},
{
  id: 46,
  question: "Which property is used to set the space between lines of text?",
  options: ["letter-spacing", "line-height", "text-spacing", "text-indent"],
  correct: "line-height",
},
{
  id: 47,
  question: "How do you apply a class called 'main' in CSS?",
  options: [".main", "#main", "main", "@main"],
  correct: ".main",
},
{
  id: 48,
  question: "Which CSS property is used to align text horizontally?",
  options: [
    "text-align",
    "text-style",
    "horizontal-align",
    "justify-content",
  ],
  correct: "text-align",
},
{
  id: 49,
  question: "Which pseudo-class is used to target an element when hovered over?",
  options: [":hover", ":focus", ":target", ":active"],
  correct: ":hover",
},
{
  id: 50,
  question: "Which property is used to specify the width of a border?",
  options: [
    "border-width",
    "border-size",
    "border-thickness",
    "border-height",
  ],
  correct: "border-width",
},
{
  id: 51,
  question: "What does the `@keyframes` rule do in CSS?",
  options: [
    "Defines an animation",
    "Applies animations to elements",
    "Controls transition timing",
    "Sets media queries",
  ],
  correct: "Defines an animation",
},
{
  id: 52,
  question: "Which CSS property is used to create a flexible layout?",
  options: ["display: flex", "position: relative", "float", "align-items"],
  correct: "display: flex",
},
{
  id: 53,
  question: "What is the purpose of the `z-index` property in CSS?",
  options: [
    "Controls stacking order of elements",
    "Adjusts element size",
    "Applies 3D transformations",
    "Sets opacity",
  ],
  correct: "Controls stacking order of elements",
},
{
  id: 54,
  question: "What is the `grid-template-columns` property used for?",
  options: [
    "Defines the structure of columns in a grid layout",
    "Aligns grid items vertically",
    "Controls the gap between grid items",
    "Specifies column text alignment",
  ],
  correct: "Defines the structure of columns in a grid layout",
},
{
  id: 55,
  question: "Which property is used to apply 3D transformations to an element?",
  options: ["transform", "perspective", "translate3d", "rotate3d"],
  correct: "transform",
},
{
  id: 56,
  question: "What does the `clip-path` property do?",
  options: [
    "Clips an element to a specified shape",
    "Aligns an element",
    "Changes background size",
    "Sets text overflow",
  ],
  correct: "Clips an element to a specified shape",
},
{
  id: 57,
  question: "What is the default value of `flex-direction` in CSS flexbox?",
  options: ["row", "column", "row-reverse", "column-reverse"],
  correct: "row",
},
{
  id: 58,
  question: "Which property is used to apply a gradient background in CSS?",
  options: [
    "background-gradient",
    "background",
    "gradient",
    "linear-gradient",
  ],
  correct: "background",
},
{
  id: 59,
  question: "Which property is used to control the speed of a transition?",
  options: [
    "transition-duration",
    "transition-speed",
    "animation-duration",
    "speed",
  ],
  correct: "transition-duration",
},
{
  id: 60,
  question: "Which value of `position` property is used to fix an element to the viewport?",
  options: ["fixed", "absolute", "relative", "sticky"],
  correct: "fixed",
}
  ];
